version: '3.7'

services:
  backend:
    image: pg-back:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    links:
      - "postgres:db"
    depends_on:
      - postgres
    volumes:
      - ./:/app

  postgres:
    image: postgres:13.7-alpine3.16
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "POSTGRES_PASSWORD=postgres pg_isready -U postgres" ]
      retries: 30
      interval: 5s
      timeout: 5s

volumes:
  postgres:
